// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.example.protos;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 로그인 성공 시 사용자 ID
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * 로그인 성공 시 사용자 ID
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * 성공 여부
   * </pre>
   *
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <pre>
   * 로그인 실패 시 에러 메시지 등
   * </pre>
   *
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 로그인 실패 시 에러 메시지 등
   * </pre>
   *
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
